# Generated by Django 4.2.1 on 2023-05-27 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('publication', models.CharField(max_length=200)),
                ('availability', models.CharField(default='No', max_length=10)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.books')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('borrowed_books', models.ManyToManyField(through='my_app.Borrowings', to='my_app.books')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.AddField(
            model_name='borrowings',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.member'),
        ),
    ]
