# Generated by Django 4.2.1 on 2023-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_registermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
