# Generated by Django 4.0.4 on 2023-05-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_registermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='user_permissions',
        ),
    ]
