# Generated by Django 4.0.4 on 2023-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_registermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='C:\\\\Users\\\\user\\\\Environments\\\\myenv\\\\Scripts\\\\LibraryManagementSystem\\\\media\\\\profile\\\\default_user.jpg', null=True, upload_to='profile/'),
        ),
    ]
