# Generated by Django 4.2.1 on 2023-05-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_registermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registermodel',
            managers=[
            ],
        ),
    ]
