# Generated by Django 4.2.1 on 2023-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_registermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
