# Generated by Django 4.2.1 on 2023-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_registermodel_address_registermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
