# Generated by Django 4.2.1 on 2023-06-01 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_alter_registermodel_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_id',
            new_name='edition',
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='publication',
            field=models.DateField(),
        ),
    ]
