# Generated by Django 4.2.1 on 2023-06-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_rename_book_id_books_edition_books_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
