# Generated by Django 4.2.1 on 2023-06-01 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_alter_borrowings_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowings',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
