# Generated by Django 4.2.1 on 2023-07-28 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_alter_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='token',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='borrowings',
            name='borrowed_date',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
        migrations.AlterField(
            model_name='borrowings',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='None', max_length=50),
        ),
    ]
