# Generated by Django 4.2.1 on 2023-07-30 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowings',
            name='borrowed_date',
            field=models.DateField(default=datetime.date(2023, 7, 30)),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
