# Generated by Django 4.2.1 on 2023-07-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_alter_borrowings_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
