# Generated by Django 4.2.1 on 2023-07-31 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowings',
            name='borrowed_date',
            field=models.DateField(default=datetime.date(2023, 7, 31)),
        ),
        migrations.AlterField(
            model_name='borrowings',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowings',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
